export const environment = {
  production: false,
  supabaseUrl: 'https://yenkuvvumgmuyvjludeg.supabase.co',
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllbmt1dnZ1bWdtdXl2amx1ZGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMDc1ODMsImV4cCI6MjA5NDY4MzU4M30.WOnAysNAhia3JubCLut7UkoGhBFWZHjyAS15SHiruT8',
  serviceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllbmt1dnZ1bWdtdXl2amx1ZGVnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTEwNzU4MywiZXhwIjoyMDk0NjgzNTgzfQ.Xwrh7MSgFhfy25ZjtBvvDJvjmtWXvmPSpJhoowWlg3w',
};